/* The Math namespace object contains static properties and methods for mathematical constants and functions.

Math works with the Number type. It doesn't work with BigInt. 


Unlike most global objects, Math is not a constructor. You cannot use it with the new operator or invoke the Atomics object as a function. All properties and methods of Math are static

Note: Many Math functions have a precision that's implementation-dependent.

This means that different browsers can give a different result. Even the same JavaScript engine on a different OS or architecture can give different results!

*/

let x;

// Square root
x = Math.sqrt(9);

// Absolute value
x = Math.abs(-5);

// Round
x = Math.round(4.2);

// Round up- always up this one resolves to 5 because 4.2 is more than 4 next whole up is 5
x = Math.ceil(4.2);

// Round down - this resolves to 4
x = Math.floor(4.9);

// Exponent  2 to the power of 3
x = Math.pow(2, 3);

// Minimum number - returns the smallest of the numbers passed in
x = Math.min(4, 5, 3);

// Maximum number returns the largest of the numbers passed in
x = Math.max(4, 5, 3);

// Get a random number/decimal between 0 and 1 - will get a random decimal between 0 and 1
x = Math.random();

// Get a random number between 1 and 100 -  multiple the decimal by 100 for1-99 adding the one so between 1 and 100
/* Math.random(): This function returns a floating-point, pseudo-random number in the range from 0 (inclusive) to 1 (exclusive). So, Math.random() generates a random decimal number between 0 and 1.

Math.random() * 100: This multiplies the random number generated by Math.random() by 100. Now, the result is a random decimal number between 0 (inclusive) and 100 (exclusive).

Math.floor(Math.random() * 100): The Math.floor() function rounds down a decimal number to the nearest whole number. So, this expression generates a random integer between 0 and 99.

Math.floor(Math.random() * 100 + 1): By adding 1 to the result, the range becomes 1 to 100. So, this expression generates a random integer between 1 and 100.

Finally, the result is assigned to the variable x: x = Math.floor(Math.random() * 100 + 1);

After this line of code is executed, the variable x will hold a random integer value between 1 and 100 (inclusive). */
x = Math.floor(Math.random() * 100 + 1);

console.log(x);
